### ISSUE TITLE
add MongoDB access to user-service

### ISSUE THREAD

**Issue by yarinsa** [snirazran/WriteSpace#19]
In user-service BE add user-service, this service is accessing the Mongo. You should also define the mongo UserSchema around there. See [here](https://docs.nestjs.com/techniques/mongodb).

DoD: from the user controller call the user service and get actual item from mongo

**Comment by snirazran** [comment]
i see alot of files in the dist folder that came with the installation of nest. do i need to open a new user-service.ts file in the dist folder or in the root of user-service?

**Comment by yarinsa** [comment]
move user.service to the root of "apps" (outside of the backend project).add list to .gitignore. And add this user.service.ts to the src folder in the nest project. Open PR
